name: senselogic_gist
description: Reusable base functions.
homepage: https://github.com/senselogic/GIST
repository: https://github.com/senselogic/GIST
version: 2.0.18

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  logger: ^2.0.2+1
  uuid: ^4.1.0

dev_dependencies:
